### ISSUE TITLE
Rules issue

### ISSUE THREAD

**Issue by Baird24** [jude-gabriel/Go-Game#18]
A gameplay/rules issue, you are not allowed to play in a position in which you would automatically die, no matter what. You should be able to place a stone in this location if it would remove enemy stones. You should be able to place in the action shown in the image just like in the example because the action of removing enemy stones comes before the action of removing your stones (when it is your turn).
The time that this is not allowed is if the stone being removed not connected to any others (it is alone) and the stone you are placing is alone and would also be removed, but that is a more advanced type of rule. 
![IMG_0283](https://user-images.githubusercontent.com/89880795/140810762-0113522c-4443-4cda-a702-5b1241118472.jpg)
![IMG_0284](https://user-images.githubusercontent.com/89880795/140810817-6180a79a-50d0-469f-a0fe-023450d0e95e.jpg)

.

**Comment by jude-gabriel** [comment]
This error has been fixed. A stone that would capture itself is now valid if it can capture opposing stones.
